#version 460
#extension GL_EXT_ray_tracing : require
#extension GL_EXT_nonuniform_qualifier : enable
#extension GL_EXT_shader_explicit_arithmetic_types_int64 : require
#extension GL_EXT_buffer_reference2 : require

// THE FIX: Declare the payload so the NVIDIA compiler doesn't delete the shader!
layout(location = 0) rayPayloadInEXT vec3 hitValue;
hitAttributeEXT vec2 attribs;

// Our dynamic memory UBO
layout(binding = 2, set = 0) uniform UBO {
	mat4 viewInverse;
	mat4 projInverse;
	vec4 lightPos[2]; 
	int vertexSize;
	int padding;
	uint64_t vertexAddressSponza;
	uint64_t indexAddressSponza;
	uint64_t vertexAddressPlane;
	uint64_t indexAddressPlane;
	uint64_t textureIndexAddressSponza;
} ubo;

// THE MASSIVE TEXTURE ARRAY
layout(binding = 3, set = 0) uniform sampler2D textures[];

layout(buffer_reference, std430, buffer_reference_align = 4) buffer Vertices { float v[]; };
layout(buffer_reference, std430, buffer_reference_align = 4) buffer Indices  { uint i[];  };
layout(buffer_reference, std430, buffer_reference_align = 4) buffer TexIndices { int id[]; };

vec2 unpackUV(Vertices verts, uint index) {
	uint floatOffset = index * (ubo.vertexSize / 4);
	return vec2(verts.v[floatOffset + 6], verts.v[floatOffset + 7]);
}

void main()
{
	// Only Sponza has vines, so ignore the mirror plane!
	if (gl_InstanceCustomIndexEXT == 0) {
		Vertices verts = Vertices(ubo.vertexAddressSponza);
		Indices  inds  = Indices(ubo.indexAddressSponza);

		ivec3 index = ivec3(inds.i[3 * gl_PrimitiveID], inds.i[3 * gl_PrimitiveID + 1], inds.i[3 * gl_PrimitiveID + 2]);

		vec2 uv0 = unpackUV(verts, index.x);
		vec2 uv1 = unpackUV(verts, index.y);
		vec2 uv2 = unpackUV(verts, index.z);

		const vec3 barycentricCoords = vec3(1.0f - attribs.x - attribs.y, attribs.x, attribs.y);
		vec2 finalUV = uv0 * barycentricCoords.x + uv1 * barycentricCoords.y + uv2 * barycentricCoords.z;

		// Fetch the exact texture ID for this specific triangle
		TexIndices texInds = TexIndices(ubo.textureIndexAddressSponza);
		int texID = texInds.id[gl_PrimitiveID];

		if (texID >= 0) {
			// textureLod forces the BVH to read the base texture without mip-map crashing
			vec4 texColor = textureLod(textures[nonuniformEXT(texID)], finalUV, 0.0);
			if (texColor.a < 0.5) {
				ignoreIntersectionEXT; // Pass through the transparent gap!
			}
		}
	}
}