#version 460
#extension GL_EXT_ray_tracing : require
#extension GL_EXT_shader_explicit_arithmetic_types_int64 : require

layout(binding = 0, set = 0) uniform accelerationStructureEXT topLevelAS;
layout(binding = 1, set = 0, rgba8) uniform image2D image;

// Update this in raygen, anyhit, and closesthit!
layout(binding = 2, set = 0) uniform UBO {
	mat4 viewInverse;
	mat4 projInverse;
	vec4 lightPos[2]; 
	int vertexSize;
	int padding;
	uint64_t vertexAddressSponza;
	uint64_t indexAddressSponza;
	uint64_t vertexAddressPlane;
	uint64_t indexAddressPlane;
	uint64_t textureIndexAddressSponza; // <--- ADDED
} ubo;

// This is the "Payload". Whenever a ray hits something, or misses, 
// the result gets written into this variable.
layout(location = 0) rayPayloadEXT vec3 hitValue;

void main() 
{
	// 1. Calculate pixel coordinates
	const vec2 pixelCenter = vec2(gl_LaunchIDEXT.xy) + vec2(0.5);
	const vec2 inUV = pixelCenter / vec2(gl_LaunchSizeEXT.xy);
	vec2 d = inUV * 2.0 - 1.0;

	// 2. Setup the Camera Ray
	vec4 origin    = ubo.viewInverse * vec4(0, 0, 0, 1);
	vec4 target    = ubo.projInverse * vec4(d.x, d.y, 1, 1);
	vec4 direction = ubo.viewInverse * vec4(normalize(target.xyz / target.w), 0);

	uint rayFlags = gl_RayFlagsNoneEXT;
	float tmin     = 0.001;
	float tmax     = 10000.0;

	// 3. Shoot the Ray!
	traceRayEXT(topLevelAS, rayFlags, 0xFF, 0, 0, 0, origin.xyz, tmin, direction.xyz, tmax, 0);

	// 4. Write the payload result to the screen
	imageStore(image, ivec2(gl_LaunchIDEXT.xy), vec4(hitValue, 1.0));
}